In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('IPL Matches 2008-2020.csv')
df.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [18]:
df['city']

0       Bangalore
1      Chandigarh
2           Delhi
3          Mumbai
4         Kolkata
          ...
811         Dubai
812         Dubai
813     Abu Dhabi
814     Abu Dhabi
815         Dubai
Name: city, Length: 816, dtype: object

In [19]:
df['city'].index

RangeIndex(start=0, stop=816, step=1)

In [20]:
df['city'].values

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Hyderabad', 'Chandigarh', 'Bangalore',
       'Chennai', 'Mumbai', 'Chandigarh', 'Bangalore', 'Kolkata', 'Delhi',
       'Hyderabad', 'Jaipur', 'Chennai', 'Hyderabad', 'Chandigarh',
       'Mumbai', 'Jaipur', 'Bangalore', 'Chennai', 'Mumbai', 'Delhi',
       'Kolkata', 'Jaipur', 'Bangalore', 'Chennai', 'Hyderabad', 'Jaipur',
       'Chandigarh', 'Kolkata', 'Mumbai', 'Chandigarh', 'Delhi', 'Mumbai',
       'Delhi', 'Jaipur', 'Hyderabad', 'Kolkata', 'Bangalore', 'Kolkata',
       'Mumbai', 'Chennai', 'Chandigarh', 'Delhi', 'Chennai', 'Bangalore',
       'Kolkata', 'Jaipur', 'Hyderabad', 'Mumbai', 'Mumbai', 'Mumbai',
       'Cape Town', 'Cape Town', 'Cape Town', 'Cape Town',
       'Port Elizabeth', 'Durban', 'Cape Town', 'Durban', 'Cape Town',
       'Durban', 'Durban', 'Port Elizabeth', 'Cape Town', 'Durban',
       'Port Elizabeth', 'Centurion', 'Durban', 'Durban', 'Centurion',
       'Centurion', 'East London', 'Durban', 'Port Elizabeth',
       'Johannesburg', 'Port Elizabeth', 'Johannesburg', 'East London',
       'Durban', 'Durban', 'Centurion', 'Centurion', 'Centurion',
       'East London', 'Kimberley', 'Kimberley', 'Port Elizabeth',
       'Johannesburg', 'Kimberley', 'Centurion', 'Centurion', 'Durban',
       'Durban', 'Durban', 'Bloemfontein', 'Port Elizabeth',
       'Johannesburg', 'Johannesburg', 'Bloemfontein', 'Centurion',
       'Johannesburg', 'Durban', 'Durban', 'Centurion', 'Centurion',
       'Centurion', 'Johannesburg', 'Johannesburg', 'Mumbai', 'Mumbai',
       'Chandigarh', 'Kolkata', 'Chennai', 'Ahmedabad', 'Bangalore',
       'Kolkata', 'Delhi', 'Bangalore', 'Delhi', 'Cuttack', 'Ahmedabad',
       'Mumbai', 'Cuttack', 'Chennai', 'Mumbai', 'Bangalore',
       'Chandigarh', 'Mumbai', 'Ahmedabad', 'Chandigarh', 'Bangalore',
       'Ahmedabad', 'Mumbai', 'Delhi', 'Mumbai', 'Chennai', 'Delhi',
       'Kolkata', 'Chandigarh', 'Chennai', 'Mumbai', 'Kolkata', 'Delhi',
       'Nagpur', 'Chennai', 'Jaipur', 'Kolkata', 'Bangalore',
       'Chandigarh', 'Nagpur', 'Bangalore', 'Delhi', 'Jaipur', 'Nagpur',
       'Mumbai', 'Chennai', 'Jaipur', 'Chennai', 'Dharamsala',
       'Bangalore', 'Kolkata', 'Dharamsala', 'Delhi', 'Kolkata', 'Mumbai',
       'Mumbai', 'Mumbai', 'Mumbai', 'Chennai', 'Hyderabad', 'Kochi',
       'Delhi', 'Mumbai', 'Kolkata', 'Jaipur', 'Bangalore', 'Chandigarh',
       'Mumbai', 'Hyderabad', 'Jaipur', 'Mumbai', 'Chennai', 'Hyderabad',
       'Mumbai', 'Kolkata', 'Kochi', 'Delhi', 'Mumbai', 'Kolkata',
       'Chandigarh', 'Mumbai', 'Kolkata', 'Delhi', 'Hyderabad', 'Jaipur',
       'Chennai', 'Delhi', 'Mumbai', 'Kochi', 'Delhi', 'Jaipur',
       'Bangalore', 'Kochi', 'Kolkata', 'Jaipur', 'Chennai', 'Mumbai',
       'Delhi', 'Hyderabad', 'Chennai', 'Mumbai', 'Kochi', 'Hyderabad',
       'Bangalore', 'Kolkata', 'Mumbai', 'Bangalore', 'Chandigarh',
       'Jaipur', 'Hyderabad', 'Chandigarh', 'Jaipur', 'Chennai', 'Indore',
       'Bangalore', 'Mumbai', 'Dharamsala', 'Indore', 'Mumbai',
       'Dharamsala', 'Chennai', 'Mumbai', 'Mumbai', 'Dharamsala', 'Delhi',
       'Bangalore', 'Kolkata', 'Mumbai', 'Mumbai', 'Chennai', 'Chennai',
       'Chennai', 'Kolkata', 'Mumbai', 'Jaipur', 'Bangalore',
       'Visakhapatnam', 'Jaipur', 'Pune', 'Visakhapatnam', 'Bangalore',
       'Delhi', 'Mumbai', 'Chennai', 'Chandigarh', 'Kolkata', 'Delhi',
       'Pune', 'Kolkata', 'Bangalore', 'Mumbai', 'Jaipur', 'Bangalore',
       'Chandigarh', 'Hyderabad', 'Chennai', 'Chandigarh', 'Chennai',
       'Delhi', 'Mumbai', 'Cuttack', 'Jaipur', 'Pune', 'Chandigarh',
       'Pune', 'Delhi', 'Chennai', 'Kolkata', 'Delhi', 'Mumbai',
       'Chennai', 'Cuttack', 'Jaipur', 'Bangalore', 'Pune', 'Chennai',
       'Kolkata', 'Chandigarh', 'Mumbai', 'Bangalore', 'Delhi', 'Pune',
       'Hyderabad', 'Mumbai', 'Jaipur', 'Pune', 'Kolkata', 'Chennai',
       'Jaipur', 'Chandigarh', 'Bangalore', 'Kolkata', 'Delhi', 'Mumbai',
       'Dharamsala', 'Delhi', 'Hyderabad', 'Dharamsala', 'Pune',
       'Hyderabad', 'Jaipur', 'Pune', 'Bangalore', 'Chennai', 'Chennai',
       'Kolkata', 'Bangalore', 'Hyderabad', 'Delhi', 'Chennai', 'Pune',
       'Hyderabad', 'Jaipur', 'Mumbai', 'Chandigarh', 'Bangalore', 'Pune',
       'Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Jaipur', 'Chennai',
       'Chandigarh', 'Bangalore', 'Pune', 'Jaipur', 'Delhi', 'Hyderabad',
       'Kolkata', 'Bangalore', 'Delhi', 'Chandigarh', 'Chennai',
       'Bangalore', 'Dharamsala', 'Kolkata', 'Chennai', 'Kolkata',
       'Jaipur', 'Mumbai', 'Chennai', 'Raipur', 'Jaipur', 'Mumbai',
       'Pune', 'Hyderabad', 'Raipur', 'Chennai', 'Pune', 'Kolkata',
       'Hyderabad', 'Bangalore', 'Mumbai', 'Jaipur', 'Bangalore',
       'Jaipur', 'Mumbai', 'Hyderabad', 'Chandigarh', 'Pune', 'Delhi',
       'Pune', 'Chandigarh', 'Ranchi', 'Jaipur', 'Delhi', 'Mumbai',
       'Ranchi', 'Chennai', 'Mumbai', 'Chandigarh', 'Hyderabad',
       'Dharamsala', 'Pune', 'Bangalore', 'Hyderabad', 'Delhi', 'Delhi',
       'Kolkata', 'Kolkata', 'Abu Dhabi', nan, 'Abu Dhabi', 'Abu Dhabi',
       nan, nan, nan, 'Abu Dhabi', nan, nan, nan, nan, nan, 'Abu Dhabi',
       'Abu Dhabi', nan, nan, nan, 'Abu Dhabi', nan, 'Ranchi', 'Mumbai',
       'Delhi', 'Bangalore', 'Ahmedabad', 'Delhi', 'Mumbai', 'Delhi',
       'Cuttack', 'Ahmedabad', 'Bangalore', 'Delhi', 'Mumbai', 'Cuttack',
       'Bangalore', 'Hyderabad', 'Ranchi', 'Bangalore', 'Hyderabad',
       'Cuttack', 'Ahmedabad', 'Ranchi', 'Hyderabad', 'Ahmedabad',
       'Delhi', 'Hyderabad', 'Kolkata', 'Chandigarh', 'Kolkata', 'Ranchi',
       'Mumbai', 'Chandigarh', 'Bangalore', 'Kolkata', 'Chandigarh',
       'Mumbai', 'Kolkata', 'Mumbai', 'Mumbai', 'Bangalore', 'Kolkata',
       'Chennai', 'Pune', 'Chennai', 'Kolkata', 'Delhi', 'Mumbai',
       'Bangalore', 'Ahmedabad', 'Kolkata', 'Pune', 'Visakhapatnam',
       'Mumbai', 'Visakhapatnam', 'Pune', 'Ahmedabad', 'Bangalore',
       'Delhi', 'Ahmedabad', 'Visakhapatnam', 'Bangalore', 'Delhi',
       'Ahmedabad', 'Mumbai', 'Chennai', 'Delhi', 'Chandigarh', 'Kolkata',
       'Bangalore', 'Chennai', 'Delhi', 'Mumbai', 'Bangalore',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Chennai', 'Kolkata',
       'Mumbai', 'Bangalore', 'Mumbai', 'Chennai', 'Kolkata', 'Raipur',
       'Mumbai', 'Chennai', 'Hyderabad', 'Raipur', 'Chandigarh', 'Mumbai',
       'Hyderabad', 'Chandigarh', 'Mumbai', 'Bangalore', 'Hyderabad',
       'Mumbai', 'Pune', 'Ranchi', 'Kolkata', 'Mumbai', 'Kolkata',
       'Chandigarh', 'Bangalore', 'Kolkata', 'Rajkot', 'Delhi',
       'Hyderabad', 'Mumbai', 'Chandigarh', 'Bangalore', 'Hyderabad',
       'Chandigarh', 'Mumbai', 'Rajkot', 'Pune', 'Delhi', 'Hyderabad',
       'Rajkot', 'Pune', 'Chandigarh', 'Hyderabad', 'Delhi', 'Mumbai',
       'Pune', 'Delhi', 'Hyderabad', 'Rajkot', 'Pune', 'Bangalore',
       'Rajkot', 'Kolkata', 'Delhi', 'Hyderabad', 'Bangalore',
       'Chandigarh', 'Visakhapatnam', 'Kolkata', 'Chandigarh',
       'Visakhapatnam', 'Bangalore', 'Hyderabad', 'Visakhapatnam',
       'Bangalore', 'Kolkata', 'Chandigarh', 'Visakhapatnam', 'Kolkata',
       'Visakhapatnam', 'Bangalore', 'Kanpur', 'Raipur', 'Visakhapatnam',
       'Kanpur', 'Kolkata', 'Raipur', 'Bangalore', 'Delhi', 'Delhi',
       'Bangalore', 'Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bengaluru',
       'Hyderabad', 'Mumbai', 'Indore', 'Pune', 'Mumbai', 'Kolkata',
       'Bangalore', 'Rajkot', 'Kolkata', 'Delhi', 'Mumbai', 'Bangalore',
       'Delhi', 'Hyderabad', 'Rajkot', 'Hyderabad', 'Indore', 'Kolkata',
       'Mumbai', 'Pune', 'Rajkot', 'Kolkata', 'Mumbai', 'Pune',
       'Bangalore', 'Kolkata', 'Chandigarh', 'Pune', 'Rajkot',
       'Chandigarh', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Kolkata',
       'Delhi', 'Bangalore', 'Hyderabad', 'Delhi', 'Bangalore',
       'Chandigarh', 'Hyderabad', 'Chandigarh', 'Kanpur', 'Mumbai',
       'Delhi', 'Kanpur', 'Kolkata', 'Pune', 'Delhi', 'Mumbai',
       'Bangalore', 'Bangalore', 'Hyderabad', 'Mumbai', 'Chandigarh',
       'Kolkata', 'Hyderabad', 'Chennai', 'Jaipur', 'Hyderabad',
       'Bengaluru', 'Mumbai', 'Kolkata', 'Bengaluru', 'Chandigarh',
       'Kolkata', 'Mumbai', 'Jaipur', 'Chandigarh', 'Pune', 'Kolkata',
       'Bengaluru', 'Hyderabad', 'Jaipur', 'Delhi', 'Mumbai', 'Bengaluru',
       'Hyderabad', 'Delhi', 'Pune', 'Jaipur', 'Bengaluru', 'Pune',
       'Bengaluru', 'Delhi', 'Kolkata', 'Indore', 'Pune', 'Hyderabad',
       'Mumbai', 'Indore', 'Hyderabad', 'Jaipur', 'Kolkata', 'Delhi',
       'Jaipur', 'Indore', 'Delhi', 'Pune', 'Mumbai', 'Indore', 'Kolkata',
       'Mumbai', 'Bengaluru', 'Delhi', 'Jaipur', 'Hyderabad', 'Delhi',
       'Pune', 'Mumbai', 'Kolkata', 'Kolkata', 'Mumbai', 'Chennai',
       'Kolkata', 'Mumbai', 'Jaipur', 'Delhi', 'Kolkata', 'Bengaluru',
       'Hyderabad', 'Chandigarh', 'Delhi', 'Hyderabad', 'Chennai',
       'Chandigarh', 'Jaipur', 'Mumbai', 'Delhi', 'Bengaluru', 'Chennai',
       'Hyderabad', 'Bengaluru', 'Jaipur', 'Chandigarh', 'Chennai',
       'Mumbai', 'Jaipur', 'Kolkata', 'Mumbai', 'Chandigarh', 'Kolkata',
       'Hyderabad', 'Mumbai', 'Chandigarh', 'Hyderabad', 'Delhi',
       'Kolkata', 'Jaipur', 'Delhi', 'Hyderabad', 'Bengaluru', 'Jaipur',
       'Chennai', 'Bengaluru', 'Kolkata', 'Chennai', 'Jaipur', 'Delhi',
       'Kolkata', 'Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai',
       'Chandigarh', 'Delhi', 'Bengaluru', 'Chandigarh', 'Mumbai',
       'Chennai', 'Visakhapatnam', 'Visakhapatnam', 'Hyderabad',
       'Abu Dhabi', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Sharjah',
       'Abu Dhabi', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Abu Dhabi',
       'Sharjah', 'Abu Dhabi', 'Dubai', 'Abu Dhabi', 'Abu Dhabi', 'Dubai',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Abu Dhabi', 'Abu Dhabi', 'Dubai',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Dubai', 'Dubai', 'Dubai',
       'Sharjah', 'Sharjah', 'Dubai', 'Abu Dhabi', 'Dubai', 'Dubai',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Abu Dhabi', 'Dubai', 'Sharjah',
       'Abu Dhabi', 'Abu Dhabi', 'Dubai', 'Dubai', 'Dubai', 'Abu Dhabi',
       'Sharjah', 'Dubai', 'Sharjah', 'Abu Dhabi', 'Dubai', 'Dubai',
       'Dubai', 'Abu Dhabi', 'Dubai', 'Dubai', 'Dubai', 'Abu Dhabi',
       'Abu Dhabi', 'Dubai'], dtype=object)

# How to find the team with most matches played?

In [15]:
df['team1'].value_counts() + df['team2'].value_counts()

Chennai Super Kings            178
Deccan Chargers                 75
Delhi Capitals                  33
Delhi Daredevils               161
Gujarat Lions                   30
Kings XI Punjab                190
Kochi Tuskers Kerala            14
Kolkata Knight Riders          192
Mumbai Indians                 203
Pune Warriors                   46
Rajasthan Royals               161
Rising Pune Supergiant          16
Rising Pune Supergiants         14
Royal Challengers Bangalore    195
Sunrisers Hyderabad            124
Name: count, dtype: int64

In [16]:
(df['team1'].value_counts() + df['team2'].value_counts()).sort_values(ascending=False)

Mumbai Indians                 203
Royal Challengers Bangalore    195
Kolkata Knight Riders          192
Kings XI Punjab                190
Chennai Super Kings            178
Delhi Daredevils               161
Rajasthan Royals               161
Sunrisers Hyderabad            124
Deccan Chargers                 75
Pune Warriors                   46
Delhi Capitals                  33
Gujarat Lions                   30
Rising Pune Supergiant          16
Kochi Tuskers Kerala            14
Rising Pune Supergiants         14
Name: count, dtype: int64

In [17]:
(df['team1'].value_counts() + df['team2'].value_counts())['Mumbai Indians']

203